name:                smtpbz
version:             1.0.1
synopsis:            Unofficial API client for smtp.bz
description:         See README.markdown
license:             BSD2
author:              Matvey Aksenov
maintainer:          matvey.aksenov@gmail.com
copyright:           2022 Matvey Aksenov
category:            Web
extra-source-files:
  - README.markdown
  - CHANGELOG.markdown
github: supki/smtpbz-unofficial

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - OverloadedStrings

library:
  dependencies:
    - aeson
    - bytestring
    - http-conduit
    - http-types
    - text
  source-dirs:
    src
  ghc-options:
    - -funbox-strict-fields
    - -Wall
    - -Werror
