name:                smtpbz-bin
version:             1.0.0
synopsis:            This is smtpbz-bin
description:         See README.markdown
license:             BSD2
author:              Matvey Aksenov
maintainer:          matvey.aksenov@gmail.com
copyright:           2022 Matvey Aksenov
extra-source-files:
  - README.markdown
  - CHANGELOG.markdown

custom-setup:
  dependencies:
    - base
    - Cabal
    - directory
    - filepath
    - process

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - OverloadedStrings

executables:
  smtpbz:
    dependencies:
      - smtpbz
      - bytestring
      - envparse
      - http-conduit
      - optparse-applicative
      - text
    source-dirs:
      driver
    main:
      Main.hs
    other-modules:
      - Cfg
      - Opts
      - Meta_smtpbz_bin
    ghc-options:
      - -Wall
      - -Werror
      - -threaded
      - -with-rtsopts=-N
